project:
  type: website
  output-dir: docs

render:
  ignore:
    - Dont-Sync-2024

website:
  title: "BU NE593"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Introduction.html
        text: Intro
      - href: Perceptron.html
        text: Perceptron
      - href: Backpropagation.html
        text: Backprop
      - href: Hopfield.html
        text: Hopfield
      - href: Linear_Algebra.html
        text: Linear Algebra
#      - href: LIF.html
#        text: LIF
#      - href: HH.html
#        text: HH

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



